### ISSUE TITLE
Deprecated `service-name` and `api-key` inputs are marked as required

### ISSUE THREAD

**Issue by breadadams** [DataDog/test-visibility-github-action#18]
It appears that the 2 deprecated inputs, `service-name` and `api-key`, are set as required, which causes this minor annoyance in my editor:

<img width="460" alt="image" src="https://github.com/user-attachments/assets/a1d20d26-4707-4c84-af7b-ca96942ecff7">

Hovering the red squiggly reveals why:

<img width="712" alt="image" src="https://github.com/user-attachments/assets/6a4f226b-8c0e-4a63-98d1-bbc72789df3b">

This is confusing as without coming here and looking in `action.yml` you'd think that `api_key` and `service` are the deprecated inputs, and that you should replace them with `service-name` and `api-key` (basically what I was about to do, before checking the source code and opening this issue 🙂).

https://github.com/DataDog/test-visibility-github-action/blob/a4ce64c0df7408dc89a965bc7f6d170a213c9c73/action.yml#L35-L43

**Comment by nikita-tkachenko-datadog** [comment]
The reason the old fields were marked as required and not the new ones is that otherwise all the existing users of the action would've had to change their workflows adding the new fields.
I didn't know the editor displayed it the way you demonstrated though.
I approved your change but I'll have to bump the major version of the action to v2 to avoid breaking things for v1 users.
